version: '3.8'

services:
  mcp-openbanking-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MCP_SERVER_URL=http://mcp-server:8080
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - mcp-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Example MCP server (replace with your actual MCP server configuration)
  mcp-server:
    image: nginx:alpine  # Replace with actual MCP server image
    ports:
      - "8080:80"
    restart: unless-stopped
    # Add your MCP server configuration here

networks:
  default:
    name: mcp-network
